### ISSUE TITLE
Add Presence Support

### ISSUE THREAD

**Issue by Loopios7** [peterthehan/create-discord-bot#14]
Add support to have the bot display a status message.

[discord.js documentation for client presence](https://discord.js.org/#/docs/main/stable/class/ClientPresence)

**Comment by peterthehan** [comment]
Hey @Loopios7, I don't think presence should be included in this template. I would like to keep it as barebones as possible and this feels like something that should be addressed at the discretion of the user.

Feel free to elaborate more/provide examples if you feel strongly about this, otherwise, I'll close this in a bit.

**Comment by Loopios7** [comment]
I feel like status messages are pretty standard even in very simple bots.
I can see how you'd prefer to leave this out, in that case a widget showcasing how to use presence would probably be helpful for people.

**Comment by peterthehan** [comment]
I think the docs are straightforward enough for implementing presence. Otherwise, the user can solicit help from the broader discord.js community.
