### ISSUE TITLE
Issues with ESLint in app and utility script.

### ISSUE THREAD

**Issue by shadowtime2000** [peterthehan/create-discord-bot#68]
While I was working on #65, the git precommit hooks failed because ESLint doesn't know which `@typescript-eslint` plugin to use, or more of which `.eslintrc.json` file to use. I feel like this is an omen for more obstacles to come, and I think we should do something about it. One solution I can think of is moving the `app` folder into another GitHub repo, and having the utility script download that.

**Comment by peterthehan** [comment]
Hmm, on one hand, I would _really_ like to keep everything under one roof... but on the other hand, with the addition of some of the recent features (particularly on the dev side), I do see the benefits of separating what really is 2 (_arguably 3..._) projects.

**Comment by peterthehan** [comment]
And I suppose if something like what you described has risen as a blocker because of the existing setup, then I guess that sort of is the proverbial _straw that breaks the camel's back_ here.

So things that need to be done here would be:
- Create new repo and move existing files in `app/` to there (this should be pretty easy)
- Update all doc references to point to new URL (easy but time-consuming)
- Create new doc (not sure what this entails yet)
- Update utility script to do `git clone` instead of existing copy logic using `fs` (a bit unsure here), we would probably get #53 for free which is a plus.
- Do some housekeeping (removing unnecessary dev deps like nodemon, remove some scripts, etc)

**Comment by shadowtime2000** [comment]
We could also use `fs-extra` to delete the `.git` folder to reset the user's source control.

**Comment by peterthehan** [comment]
I'll look into this tomorrow and try to unblock asap.

**Comment by shadowtime2000** [comment]
One thing to think about is how are we going to allow update the core bot files

**Comment by peterthehan** [comment]
Yup have that as an open question in the 4 bullet point. Unsure atm.

**Comment by shadowtime2000** [comment]
For updating the project we could try merging with the template repo and then resolving conflicts by overriding anything that we need to change and leaving everything else the same.

**Comment by shadowtime2000** [comment]
Nvm

**Comment by peterthehan** [comment]
https://github.com/peterthehan/discord-bot Made a new repo, basically just copy-pasted stuff in `app/` to there.

**Comment by peterthehan** [comment]
Closing since we already track this in #69.
